<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../ITStockM.Domain/ITStockM.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="System.Linq.Dynamic.Core" />
  </ItemGroup>

</Project>
